authorization:
  consumer_key: please setting!!!
  consumer_secret: please setting!!!
  access_token: please setting!!!
  access_token_secret: please setting!!!
client:
  default_search_word: プログラミング
  default_search_count: 80
  default_search_term: 7
tweet:
  favorite_threshold_count: 1
user:
  followers_threshold_count: 80
  friends_threshold_count: 80