authorization:
  consumer_key: <%= ENV['CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['CONSUMER_SECRET'] %>
  access_token: <%= ENV['ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['ACCESS_TOKEN_SECRET'] %>
client:
  default_search_word: プログラミング
  default_search_count: 60
  default_search_term: 7
tweet:
  favorite_threshold_count: 1
user:
  followers_threshold_count: 80
  friends_threshold_count: 80